version: '3.8'

services:
  # 1. Zookeeper: Kafka의 메타데이터 관리 및 클러스터 상태 조율
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    # 주키퍼가 실제로 연결을 받을 준비가 됐는지 체크
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Kafka: 고빈도 위치 이벤트를 수집하고 전달하는 스트리밍 브로커
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092" # 외부(Host PC) 접속 포트
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      # 내부(Docker 컨테이너)와 외부(호스트 PC) 접속 리스너 분리 설정
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      
      # Spring Boot 등 호스트 앱은 localhost:9092로, 컨테이너끼리는 kafka:29092로 통신
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${KAFKA_EXTERNAL_HOST:-localhost}:9092

      # 브로커 간 내부 통신용 리스너 지정
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      # 테스트 환경이므로 복제본(Replication) 수를 1개로 제한
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 3. Redis: 최신 위치 상태를 유지하는 고속 인메모리 DB
  # '서버 사이드 동맥 경화' 방지를 위해 디스크 I/O 없이 초저지연 상태 관리 지원 [cite: 43, 80]
  redis:
    image: redis/redis-stack:7.4.0-v6
    ports:
      - "6379:6379"
      - "127.0.0.1:8001:8001"
    # 실시간성 극대화를 위해 디스크 스냅샷(저장) 기능 비활성화 [cite: 101]
    command: redis-server --save ""