global:
  scrape_interval: 2s # 2초마다 수집 (실시간성 강조)

scrape_configs:
  - job_name: 'itrc-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080' # LBS-Producer (신규 추가)
          - 'host.docker.internal:8081' # Consumer
          - 'host.docker.internal:8082' # 기존 모듈 (Kafka/RDBMS)
        labels:
          project: 'ICN-LBS-Project'