global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'itrc-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'host.docker.internal:8081'
          - 'host.docker.internal:8082'
          - 'host.docker.internal:8083'
        labels:
          project: 'ICN-LBS-Project'